import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'background': '#0b0e14',
        'surface': '#0b0e14',
        'surface-dim': '#0b0e14',
        'surface-container-lowest': '#000000',
        'surface-container-low': '#10131a',
        'surface-container': '#161a21',
        'surface-container-high': '#1c2028',
        'surface-container-highest': '#22262f',
        'surface-bright': '#282c36',
        'surface-variant': '#22262f',
        'on-surface': '#ecedf6',
        'on-background': '#ecedf6',
        'on-surface-variant': '#a9abb3',
        'primary': '#81ecff',
        'primary-dim': '#00d4ec',
        'primary-fixed': '#00e3fd',
        'primary-fixed-dim': '#00d4ec',
        'primary-container': '#00e3fd',
        'on-primary': '#005762',
        'on-primary-container': '#004d57',
        'on-primary-fixed': '#003840',
        'on-primary-fixed-variant': '#005762',
        'inverse-primary': '#006976',
        'secondary': '#dd8bfb',
        'secondary-dim': '#ce7eec',
        'secondary-fixed': '#f2c1ff',
        'secondary-fixed-dim': '#ebadff',
        'secondary-container': '#6e208c',
        'on-secondary': '#4c0068',
        'on-secondary-container': '#f1bfff',
        'on-secondary-fixed': '#580078',
        'on-secondary-fixed-variant': '#792c97',
        'tertiary': '#c6a2ff',
        'tertiary-dim': '#b28af1',
        'tertiary-fixed': '#c49fff',
        'tertiary-fixed-dim': '#b790f7',
        'tertiary-container': '#ba92fa',
        'on-tertiary': '#42177d',
        'on-tertiary-container': '#370471',
        'on-tertiary-fixed': '#23004e',
        'on-tertiary-fixed-variant': '#492084',
        'error': '#ff716c',
        'error-dim': '#d7383b',
        'error-container': '#9f0519',
        'on-error': '#490006',
        'on-error-container': '#ffa8a3',
        'outline': '#73757d',
        'outline-variant': '#45484f',
        'surface-tint': '#81ecff',
        'inverse-surface': '#f9f9ff',
        'inverse-on-surface': '#52555c',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, #81ecff, #dd8bfb)',
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
      },
      boxShadow: {
        'neon-primary': '0 0 20px rgba(129, 236, 255, 0.3)',
        'neon-secondary': '0 0 20px rgba(221, 139, 251, 0.3)',
        'ambient': '0 20px 40px rgba(236, 237, 246, 0.04)',
        'lume': '0 0 15px rgba(215, 56, 59, 0.4)',
        'card-hover': '0 20px 60px rgba(129, 236, 255, 0.1)',
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'gradient-shift': 'gradientShift 8s ease infinite',
        'fade-up': 'fadeUp 0.6s ease forwards',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        gradientShift: {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}
export default config
